-- Nexora Ventures production schema blueprint (PostgreSQL)
CREATE TABLE users (id UUID PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, full_name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'USER', status TEXT NOT NULL DEFAULT 'ACTIVE', email_verified BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE kyc_profiles (id UUID PRIMARY KEY, user_id UUID UNIQUE NOT NULL REFERENCES users(id), status TEXT NOT NULL DEFAULT 'PENDING', document_type TEXT, private_document_ref TEXT, reviewed_by UUID REFERENCES users(id), reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE projects (id UUID PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT NOT NULL, category TEXT, status TEXT NOT NULL DEFAULT 'DRAFT', target_amount NUMERIC(20,2), minimum_amount NUMERIC(20,2), risk_level TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE investments (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), project_id UUID NOT NULL REFERENCES projects(id), amount NUMERIC(20,2) NOT NULL, ownership_percentage NUMERIC(12,6), status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE transactions (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), investment_id UUID REFERENCES investments(id), type TEXT NOT NULL, amount NUMERIC(20,2) NOT NULL, currency CHAR(3) NOT NULL, provider_reference TEXT, status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE documents (id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), project_id UUID REFERENCES projects(id), document_type TEXT NOT NULL, private_storage_ref TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE notifications (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), title TEXT NOT NULL, message TEXT NOT NULL, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE audit_logs (id UUID PRIMARY KEY, admin_id UUID NOT NULL REFERENCES users(id), action TEXT NOT NULL, entity TEXT NOT NULL, entity_id UUID, ip_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
-- Sensitive documents and secrets must live outside this public GitHub repository.